# Generated by Django 5.2.9 on 2025-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=70)),
                ('branch', models.CharField(max_length=60)),
            ],
        ),
    ]
